run:
  tests: false
  timeout: 5m
linters:
  enable-all: true
  disable:
    - lll
    - gocyclo
    - interfacer
    - unparam
    - gocritic
    - dupl
    - errcheck
    - gochecknoglobals
    - funlen
    - gocognit
    - godox
    - wsl
    - exhaustivestruct
    - nlreturn
    - wrapcheck
    - prealloc
    - goerr113 # fixing this (returning wrapped static error types) should be a TODO at some point, not worrying about it now.
    - cyclop
