name: walrus
on:
  pull_request:

jobs:

  test:
    timeout-minutes: 5
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.13' # oldest supported version
        - '1.16' # latest version
    steps:
    - 
      name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Test
      run: make test
    - 
      name: Build
      run: make
